export const translations = {
    en: {
        score: "Score",
        best: "Best",
        maxTile: "Max Tile",
        games: "Games",
        reset: "Reset",
        glow: "Glow",
        music: "Music",
        winMessage: "You Win! Keep playing?",
        gameOver: "Game Over!",
        menu: "Menu",
        save: "Save",
        saving: "Saving...",
        saved: "Saved!",
        saveError: "Error!",
        play: "Play",
        continue: "Continue"
    },
    ru: {
        score: "Счёт",
        best: "Рекорд",
        maxTile: "Макс. куб",
        games: "Игр",
        reset: "Сброс",
        glow: "Сияние",
        music: "Музыка",
        winMessage: "Победа! Продолжить игру?",
        gameOver: "Игра окончена!",
        menu: "Меню",
        save: "Сохранить",
        saving: "Сохраняем...",
        saved: "Сохранено!",
        saveError: "Ошибка!",
        play: "Играть",
        continue: "Продолжить"
    },
    fr: {
        score: "Score",
        best: "Meilleur",
        maxTile: "Tuile max",
        games: "Parties",
        reset: "Réinitialiser",
        glow: "Lueur",
        music: "Musique",
        winMessage: "Vous avez gagné ! Continuer à jouer ?",
        gameOver: "Partie terminée!",
        menu: "Menu",
        save: "Sauvegarder",
        saving: "Sauvegarde...",
        saved: "Sauvegardé !",
        saveError: "Erreur !",
        play: "Jouer",
        continue: "Continuer"
    },
    it: {
        score: "Punteggio",
        best: "Migliore",
        maxTile: "Max Tessera",
        games: "Giochi",
        reset: "Reset",
        glow: "Bagliore",
        music: "Musica",
        winMessage: "Hai vinto! Vuoi continuare a giocare?",
        gameOver: "Gioco finito!",
        menu: "Menu",
        save: "Salva",
        saving: "Salvataggio...",
        saved: "Salvato!",
        saveError: "Errore!",
        play: "Gioca",
        continue: "Continua"
    },
    de: {
        score: "Punkte",
        best: "Best",
        maxTile: "Max Kachel",
        games: "Spiele",
        reset: "Zurücksetzen",
        glow: "Glanz",
        music: "Musik",
        winMessage: "Du hast gewonnen! Weiterspielen?",
        gameOver: "Spiel beendet!",
        menu: "Menü",
        save: "Speichern",
        saving: "Wird gespeichert...",
        saved: "Gespeichert!",
        saveError: "Fehler!",
        play: "Spielen",
        continue: "Fortsetzen"
    },
    es: {
        score: "Puntuación",
        best: "Mejor",
        maxTile: "Máx ficha",
        games: "Juegos",
        reset: "Reiniciar",
        glow: "Brillo",
        music: "Música",
        winMessage: "¡Has ganado! ¿Quieres seguir jugando?",
        gameOver: "¡Fin del juego!",
        menu: "Menú",
        save: "Guardar",
        saving: "Guardando...",
        saved: "¡Guardado!",
        saveError: "¡Error!",
        play: "Jugar",
        continue: "Continuar"
    },
    zh: {
        score: "得分",
        best: "最佳",
        maxTile: "最大方块",
        games: "游戏",
        reset: "重置",
        glow: "辉光",
        music: "音乐",
        winMessage: "你赢了！继续玩吗？",
        gameOver: "游戏结束！",
        menu: "菜单",
        save: "保存",
        saving: "保存中...",
        saved: "已保存！",
        saveError: "错误！",
        play: "开始",
        continue: "继续"
    },
    pt: {
        score: "Pontuação",
        best: "Melhor",
        maxTile: "Máx Peça",
        games: "Jogos",
        reset: "Reiniciar",
        glow: "Brilho",
        music: "Música",
        winMessage: "Você venceu! Deseja continuar jogando?",
        gameOver: "Fim de jogo!",
        menu: "Menu",
        save: "Salvar",
        saving: "Salvando...",
        saved: "Salvo!",
        saveError: "Erro!",
        play: "Jogar",
        continue: "Continuar"
    },
    ko: {
        score: "점수",
        best: "최고",
        maxTile: "최대 타일",
        games: "게임",
        reset: "초기화",
        glow: "광택",
        music: "음악",
        winMessage: "승리했습니다! 계속 플레이하시겠습니까?",
        gameOver: "게임 오버!",
        menu: "메뉴",
        save: "저장",
        saving: "저장 중...",
        saved: "저장됨!",
        saveError: "오류!",
        play: "플레이",
        continue: "계속"
    },
    ja: {
        score: "スコア",
        best: "ベスト",
        maxTile: "最大タイル",
        games: "ゲーム数",
        reset: "リセット",
        glow: "グロー",
        music: "音楽",
        winMessage: "勝利！続けて遊びますか？",
        gameOver: "ゲームオーバー！",
        menu: "メニュー",
        save: "保存",
        saving: "保存中...",
        saved: "保存完了！",
        saveError: "エラー！",
        play: "プレイ",
        continue: "続ける"
    },
    tr: {
        score: "Skor",
        best: "En İyi",
        maxTile: "Maks Taş",
        games: "Oyunlar",
        reset: "Sıfırla",
        glow: "Parıltı",
        music: "Müzik",
        winMessage: "Kazandınız! Oynamaya devam etmek ister misiniz?",
        gameOver: "Oyun bitti!",
        menu: "Menü",
        save: "Kaydet",
        saving: "Kaydediliyor...",
        saved: "Kaydedildi!",
        saveError: "Hata!",
        play: "Oyna",
        continue: "Devam et"
    },
    ar: {
        score: "النقاط",
        best: "الأفضل",
        maxTile: "أكبر بلاطة",
        games: "الألعاب",
        reset: "إعادة ضبط",
        glow: "وهج",
        music: "موسيقى",
        winMessage: "لقد فزت! هل تريد الاستمرار في اللعب؟",
        gameOver: "انتهت اللعبة!",
        menu: "القائمة",
        save: "حفظ",
        saving: "جارٍ الحفظ...",
        saved: "تم الحفظ!",
        saveError: "خطأ!",
        play: "ابدأ اللعب",
        continue: "تابع"
    },
    hi: {
        score: "स्कोर",
        best: "सर्वश्रेष्ठ",
        maxTile: "अधिकतम टाइल",
        games: "खेल",
        reset: "रीसेट",
        glow: "चमक",
        music: "संगीत",
        winMessage: "आप जीत गए! क्या आप खेलना जारी रखना चाहेंगे?",
        gameOver: "खेल खत्म!",
        menu: "मेनू",
        save: "सेव करें",
        saving: "सेव हो रहा है...",
        saved: "सेव हो गया!",
        saveError: "त्रुटि!",
        play: "खेलें",
        continue: "जारी रखें"
    },
    id: {
        score: "Skor",
        best: "Terbaik",
        maxTile: "Ubin Maks",
        games: "Permainan",
        reset: "Reset",
        glow: "Cahaya",
        music: "Musik",
        winMessage: "Anda menang! Mau lanjut bermain?",
        gameOver: "Permainan berakhir!",
        menu: "Menu",
        save: "Simpan",
        saving: "Menyimpan...",
        saved: "Tersimpan!",
        saveError: "Kesalahan!",
        play: "Mainkan",
        continue: "Lanjutkan"
    },
};

// Helper to get GamePush language or fallback
export function getUserLanguage() {
    if (window.gamePushSDK && window.gamePushSDK.language) {
        return translations[window.gamePushSDK.language] ? window.gamePushSDK.language : "en";
    }
    return "en";
}