export const translations = {
    en: {
        score: "Score",
        best: "Best",
        maxTile: "Max Tile",
        games: "Games",
        reset: "Reset",
        glow: "Glow",
        music: "Music",
        winMessage: "You Win! Keep playing?",
    },
    ru: {
        score: "Счёт",
        best: "Рекорд",
        maxTile: "Макс. куб",
        games: "Игр",
        reset: "Сброс",
        glow: "Сияние",
        music: "Музыка",
        winMessage: "Победа! Продолжить игру?",
    },
    fr: {
        score: "Score",
        best: "Meilleur",
        maxTile: "Tuile max",
        games: "Parties",
        reset: "Réinitialiser",
        glow: "Lueur",
        music: "Musique",
        winMessage: "Vous avez gagné ! Continuer à jouer ?",
    },
    it: {
        score: "Punteggio",
        best: "Migliore",
        maxTile: "Max Tessera",
        games: "Giochi",
        reset: "Reset",
        glow: "Bagliore",
        music: "Musica",
        winMessage: "Hai vinto! Vuoi continuare a giocare?",
    },
    de: {
        score: "Punkte",
        best: "Best",
        maxTile: "Max Kachel",
        games: "Spiele",
        reset: "Zurücksetzen",
        glow: "Glanz",
        music: "Musik",
        winMessage: "Du hast gewonnen! Weiterspielen?",
    },
    es: {
        score: "Puntuación",
        best: "Mejor",
        maxTile: "Máx ficha",
        games: "Juegos",
        reset: "Reiniciar",
        glow: "Brillo",
        music: "Música",
        winMessage: "¡Has ganado! ¿Quieres seguir jugando?",
    },
    zh: {
        score: "得分",
        best: "最佳",
        maxTile: "最大方块",
        games: "游戏",
        reset: "重置",
        glow: "辉光",
        music: "音乐",
        winMessage: "你赢了！继续玩吗？",
    },
    pt: {
        score: "Pontuação",
        best: "Melhor",
        maxTile: "Máx Peça",
        games: "Jogos",
        reset: "Reiniciar",
        glow: "Brilho",
        music: "Música",
        winMessage: "Você venceu! Deseja continuar jogando?",
    },
    ko: {
        score: "점수",
        best: "최고",
        maxTile: "최대 타일",
        games: "게임",
        reset: "초기화",
        glow: "광택",
        music: "음악",
        winMessage: "승리했습니다! 계속 플레이하시겠습니까?",
    },
    ja: {
        score: "スコア",
        best: "ベスト",
        maxTile: "最大タイル",
        games: "ゲーム数",
        reset: "リセット",
        glow: "グロー",
        music: "音楽",
        winMessage: "勝利！続けて遊びますか？",
    },
    tr: {
        score: "Skor",
        best: "En İyi",
        maxTile: "Maks Taş",
        games: "Oyunlar",
        reset: "Sıfırla",
        glow: "Parıltı",
        music: "Müzik",
        winMessage: "Kazandınız! Oynamaya devam etmek ister misiniz?",
    },
    ar: {
        score: "النقاط",
        best: "الأفضل",
        maxTile: "أكبر بلاطة",
        games: "الألعاب",
        reset: "إعادة ضبط",
        glow: "وهج",
        music: "موسيقى",
        winMessage: "لقد فزت! هل تريد الاستمرار في اللعب؟",
    },
    hi: {
        score: "स्कोर",
        best: "सर्वश्रेष्ठ",
        maxTile: "अधिकतम टाइल",
        games: "खेल",
        reset: "रीसेट",
        glow: "चमक",
        music: "संगीत",
        winMessage: "आप जीत गए! क्या आप खेलना जारी रखना चाहेंगे?",
    },
    id: {
        score: "Skor",
        best: "Terbaik",
        maxTile: "Ubin Maks",
        games: "Permainan",
        reset: "Reset",
        glow: "Cahaya",
        music: "Musik",
        winMessage: "Anda menang! Mau lanjut bermain?",
    },
};

// Helper to get GamePush language or fallback
export function getUserLanguage() {
    if (window.gamePushSDK && window.gamePushSDK.language) {
        return translations[window.gamePushSDK.language] ? window.gamePushSDK.language : "en";
    }
    return "en";
}